INTRODUCTION

In [211]:
import numpy as np

In [212]:
# shape
a=np.array([[1,2,3],[4,5,6]])
a.shape
a

array([[1, 2, 3],
       [4, 5, 6]])

In [213]:
# slicing
a=np.array([1,2,3,4,5,6])
# a[:3]

#actual location not copy
b=a[3 :]
print(b)

b[0]=99

print(a)

[4 5 6]
[ 1  2  3 99  5  6]


In [214]:
# dimension is axis 2d array so 2 axis

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print(a[2,1])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
10


ARRAY ATTRIBUTES

In [215]:
a.ndim
a.shape

len(a.shape)== a.ndim

a.size

import math
a.size== math.prod(a.shape)

a.dtype


dtype('int64')

Creating Basic Arrays

In [216]:

np.zeros(4)
np.ones(3)
np.empty(4)

array([0., 0., 0., 0.])

In [217]:
np.arange(4)

array([0, 1, 2, 3])

In [218]:
np.linspace(0,10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [219]:
x=np.ones(2,dtype=np.int64)
x

array([1, 1])

Add Remove Sort

In [220]:
arr=np.array([4,3,2,1,5,6,7])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7])

In [221]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [222]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6]])


np.concatenate((x,y),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [223]:
# size shape dim

array_example = np.array(
    [
        [[0, 1, 2, 3], [4, 5, 6, 7]],
        [[0, 1, 2, 3], [4, 5, 6, 7]],
        [[0, 1, 2, 3], [4, 5, 6, 7]],
    ]
)

array_example.ndim
array_example.size
array_example.shape



(3, 2, 4)

In [224]:
# reshape

a=np.arange(6)

print(a)

b=a.reshape(3,2)
print(b)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


In [225]:
np.array([1,2,3,4,5,6])
a.shape

a2=a[np.newaxis, :]
a2.shape


(1, 6)

In [226]:
# newaxis 
row_vector=a[np.newaxis, :]
row_vector.shape

print(row_vector)


col_vector=a[:, np.newaxis]
col_vector.shape

print(col_vector)

[[0 1 2 3 4 5]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [227]:
# expand_dims 
a = np.array([1, 2, 3, 4, 5, 6])
a.shape


b=np.expand_dims(a,axis=1)
print(b)

c=np.expand_dims(a,axis=0)
print(c)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3 4 5 6]]


INDEXING AND SLICING

In [228]:
data=np.array([1,2,3])

data[0:2]
data[1:]
data[-2:]


array([2, 3])

In [229]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(a[a<5])

five_up=a>=5
print(a[five_up])

[1 2 3 4]
[ 5  6  7  8  9 10 11 12]


In [230]:
div2=a[a%2==0]

print(div2)

[ 2  4  6  8 10 12]


In [231]:
c=a[(a>2) & (a<11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [232]:
five_up=(a>5) | (a==5)
print(five_up)
print(a)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [233]:
b=np.nonzero(a<5)
# print(b)

list_of_coordinates=list(zip(b[0],b[1]))

for coord in list_of_coordinates:
    print(coord)
    

print(a[b])

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))
[1 2 3 4]


How to create an array from existing data

In [234]:
a=np.array([1,2,3,4,5,6,7,8,9,10])

arr1=a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [235]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

np.vstack((a1,a2))

np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [236]:
x=np.arange(1,25).reshape(2,12)
x
np.hsplit(x,3)

np.hsplit(x,(3,4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [237]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b1=a[0,:]
b1
b1[0]=999

print(a)

[[999   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


Basic array operations-----------
This section covers addition, subtraction, multiplication, division, and more

In [238]:
data=np.array([1,2])
ones=np.ones(2, dtype=int)

data+ones
data-ones
data/ones
data*ones

array([1, 2])

In [239]:
a=np.array([1,2,3,4])
a.sum()

np.int64(10)

In [240]:
b=np.array([[1,1],
            [2,2]])

# b.sum(axis=1)
np.sum(b,axis=0)
np.sum(b,axis=1)

array([2, 4])

Broadcasting

In [241]:
data=np.array([1,2])
data*1.6

array([1.6, 3.2])

In [242]:
data=np.array([1,2,3])

data.max()
data.min()
data.sum()

np.int64(6)

In [243]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
a.sum()
a.min()

a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [244]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

data[0,1]
data[1:3]

# first part selects row, then column 
data[0:2,0]

data.max()
data.min()
data.sum()

np.int64(21)

In [245]:
data=np.array([[1,2],[5,3],[4,6]])
data
data.max(axis=0)
data.max(axis=1)

array([2, 5, 6])

In [246]:
data=np.array([[1,2],[3,4]], dtype=int)
ones=np.ones((2,2), dtype=int)

data+ones

array([[2, 3],
       [4, 5]])

In [247]:
data=np.array([[1,2],[3,4],[5,6]])

ones_row=np.ones(2)

data+ones_row

array([[2., 3.],
       [4., 5.],
       [6., 7.]])

In [248]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [249]:
np.ones(3)

np.zeros(3)

# random 

rng=np.random.default_rng()
rng.random(3)

np.random.default_rng().random(30)

np.random.random(5)



array([0.76181705, 0.05232226, 0.8559501 , 0.69122705, 0.91244845])

Generating random numbers


In [250]:
rng.integers(9,size=(2,4)) #less than 9



array([[8, 6, 0, 0],
       [5, 3, 4, 2]])

How to get unique items and counts


In [251]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values=np.unique(a)
unique_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [252]:
unique_values, indices_list=np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [253]:
unique_values, occurrances_count=np.unique(a, return_counts=True)
print(occurrances_count)

[3 2 2 2 1 1 1 1 1 1]


In [254]:
# for 2d arrays

a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

unique_values=np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [255]:
unique_rows=np.unique(a_2d, axis=0)
unique_rows

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [256]:
unique_rows, indices, occurrances_count=np.unique(a_2d, axis=0, return_counts=True, return_index=True)

# pprint all unique rows 
print(unique_rows)
# indices of the rows firs occurrance 
print(indices)
# count of the occurrances 
print(occurrances_count)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 1 1]


Transposing and reshaping a matrix

In [257]:
data=np.array([[1,2],[3,4],[5,6]])
data.reshape(2,3)

data.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [258]:
arr=np.arange(6).reshape((2,3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [259]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [260]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

How to reverse an array

In [261]:
arr=np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [262]:
reversed_arr=np.flip(arr)
reversed_arr

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

In [263]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


In [264]:
reversed_arr=np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [265]:
# reversing rows 

reversed_arr_rows=np.flip(arr_2d,axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [267]:
# reversing columns 

reversed_arr_cols=np.flip(arr_2d,axis=1)
print(reversed_arr_cols)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [268]:
# reversing only one row 
arr_2d[1]=np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [269]:
arr_2d[:,1]=np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


Reshaping and flattening multidimensional arrays

In [ ]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.flatten()

In [ ]:
a1 = x.flatten()
a1[0] = 99
print(x)  # Original array
print(a1)  # New array

In [ ]:
a2 = x.ravel()
a2[0] = 98
print(x)  # Original array
print(a2)  # New array