In [1]:
import numpy as  np

In [4]:
a=np.array([1,2,3])
b=np.array([[1,2,3],[4,5,6]])
c=np.array([[[1,2,3],[4,5,6]],[[3,2,1],[6,5,4]]])

print(a,'\n\n',b,'\n\n',c)

[1 2 3] 

 [[1 2 3]
 [4 5 6]] 

 [[[1 2 3]
  [4 5 6]]

 [[3 2 1]
  [6 5 4]]]


In [ ]:
d=np.arange(10,25,5) #start atop step
print(d)



[10 15 20]


In [ ]:
np.linspace(0,2,9)#0 to 2 with 9 steps

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [10]:
e=np.full((2,2),7)
print(e)

[[7 7]
 [7 7]]


In [11]:
f=np.eye(2)
print(f)

[[1. 0.]
 [0. 1.]]


In [ ]:
# saving to disk 
# Code	----------------------------------------  Purpose
# np.save('my_array', a)	Save array a to my_array.npy
# np.savez('array.npz', a, b)	Save a and b into array.npz
# np.load('my_array.npy')	Load the array stored in my_array.npy
a=np.array([1,2,3])
b=np.array([[1,2,3],[4,5,6]])
c=np.array([[[1,2,3],[4,5,6]],[[3,2,1],[6,5,4]]])

np.save('my_array',a)
np.savez('array.npz',a,b)
np.load('my_array.npy')
np.load('array.npz')

NpzFile 'array.npz' with keys: arr_0, arr_1

In [17]:
# loading

np.loadtxt('myfile.txt')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])