In [21]:
import numpy as np

In [22]:
a=np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [23]:
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [24]:
a.ndim

1

In [25]:
b.shape

(2, 4)

In [26]:
a.dtype

dtype('int32')

In [27]:
a.itemsize

4

In [28]:
a.size * a.itemsize
a.nbytes

12

In [31]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [33]:
a[1,-2]

np.int64(13)

In [34]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [35]:
a[:,2]

array([ 3, 10])

In [37]:
a[0,1:6:2]

array([2, 4, 6])

In [39]:
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
