In [1]:
import numpy as np
import pandas as pd

In [20]:
a=np.array([1,2,3,4,5,6])
print(np.mean(a))

3.5


In [22]:
a=np.array([1,2,3])
print(type(a))

print(a.shape)

b=np.array([[1,2],[3,4]])
print(b.shape)


<class 'numpy.ndarray'>
(3,)
(2, 2)


In [30]:
d=np.zeros((2,3))
print('e--',d)

e=np.ones((4,2))
print('e--',e)

f=np.full((2,2),9)
print('e--',f)

g=np.random.random((3,3))
print('e--',g)

h=np.empty((2,2))
print('e--',h)

e-- [[0. 0. 0.]
 [0. 0. 0.]]
e-- [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
e-- [[9 9]
 [9 9]]
e-- [[0.37083616 0.90439099 0.14916648]
 [0.77409017 0.66287286 0.71307887]
 [0.6106821  0.68307205 0.83810691]]
e-- [[4.4e-323 4.4e-323]
 [4.4e-323 4.4e-323]]


In [2]:
h=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print('h--',h)

i=h[0:2,1:3]
print("i--",i)


h=np.zeros((3,3))
i=h[0:2,0:2].copy()
h[0,0]=99
print(h)
print(i)

print(h.dtype)

# force data type 
l=np.array([1.0,2.0],dtype=np.int64)
print(l.dtype)


h-- [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
i-- [[2 3]
 [6 7]]
[[99.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[0. 0.]
 [0. 0.]]
float64
int64


In [7]:
# array arithmatics 
x=np.array([[1,2],[3,4]], dtype=np.float64)
y=np.array([[5,6],[7,8]], dtype=np.float64)

# element wise sum
print(x+y) 
print(np.add(x,y))

# element wise difference 
print(x-y)
print(np.subtract(x,y))

#element wise product
print(x*y)
print(np.multiply(x,y))

#element wise division
print(x/y)
print(np.divide(x,y))


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [12]:
# operations on a single array
x=np.array([[1,2],[3,4]])
print(x)

print(np.sum(x))

#col sum
print(np.sum(x,axis=0))
# row sum 
print(np.sum(x,axis=1))

# mean of all 
print(np.mean(x))
# col mean 
print(np.mean(x,axis=0))
# row mean 
print(np.mean(x,axis=1))


[[1 2]
 [3 4]]
10
[4 6]
[3 7]
2.5
[2. 3.]
[1.5 3.5]
